site_name: Platform Documentation
plugins:
  - search
  # - monorepo
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

nav:
  - Summaries: 
    - Home: 'index.md'
    - Markdown Cheat Sheet: 'markdown.md'
    - Kubernetes: 'kubernetes.md'
    - Object Orientation in Go: 'go.md'
    # - GitOps: 'concept_gitops.md'


theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    # - content.action.edit
    # - content.action.view
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: navy
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  # favicon: images/asml--600.png

extra:
  # social:
  #   - icon: fontawesome/solid/envelope
  #     link: mailto:val.grimm@asml.com
  #     name: Email to Tech Writer
  generator: false
# repo_url: https://github.com/asml-gh/dpng-platform-docs

# site_favicon: mages/asml--600.png
copyright: Copyright &copy; 2023, EK